[pytest]
addopts = -v -W ignore::DeprecationWarning
env =
    # [FIX] Force l'utilisation d'une base de données de test locale (SQLite en mémoire)
    # pour isoler les tests de l'environnement de développement Docker.
    DATABASE_URL=sqlite+aiosqlite:///./test_temp.db
    PYTHONPATH=.:backend