server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Indispensable pour React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # [FIX EXPERT] Interdire la mise en cache de l'index pour forcer le navigateur à lire le nouveau code
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
    }
}